### ISSUE TITLE
correct syntax?

### ISSUE THREAD

**Issue by crimsdings** [Neph0/steamMarketWatcher#1]
i dont understand the correct syntax for items like 
http://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20M4A1-S%20%7C%20Blood%20Tiger%20%28Minimal%20Wear%29?l=english - the name of the item is "StatTrak™ M4A1-S | Blood Tiger" but it seems to find nothing. Also it seems like there is no "item not found" output ?

i think the ™ is a problem ..

**Comment by Neph0** [comment]
Hello,

Sorry for not correcting this issue but I had completely forgotten about this repo until now. Unfortunately steam have heavily changed their pages' source and I don't feel like updating the project. :disappointed:

**Comment by Neph0** [comment]
Actually it felt wrong to just sweep this issue off... I updated the script to match Steam's new pages. Now it works with products of every game (was only for DotA2 before because I'm dumb and there was something rather important that I didn't even notice).

I fixed the unicode characters problem, too. Hope you can make use of this script now... One year later :sweat_smile:
